# Generated by Django 6.0 on 2026-01-24 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_notified_driver',
            field=models.ForeignKey(blank=True, help_text='Driver currently being notified (Uber-like queue)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('searching_driver', 'Searching for Driver'), ('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('accepted', 'Accepted'), ('started', 'On the Way'), ('arrived', 'Arrived/Working'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_driver_available', 'No Driver Available')], default='pending', max_length=25),
        ),
    ]
