# Generated by Django 6.0 on 2026-01-24 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_current_notified_driver_alter_booking_status'),
        ('tracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverlocation',
            options={'verbose_name': 'Driver Location', 'verbose_name_plural': 'Driver Locations'},
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DriverOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Distance from driver to pickup location in km')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('queue_position', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='bookings.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Order Request',
                'verbose_name_plural': 'Driver Order Requests',
                'ordering': ['booking', 'queue_position'],
                'unique_together': {('booking', 'driver')},
            },
        ),
    ]
